// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"acheron_server/internal/biz"
	"acheron_server/internal/conf"
	"acheron_server/internal/data"
	"acheron_server/internal/server"
	"acheron_server/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, music *conf.Music, logger *slog.Logger) (*kratos.App, func(), error) {
	musicRepo, cleanup, err := data.NewMusicRepo(music)
	if err != nil {
		return nil, nil, err
	}
	musicUsecase := biz.NewMusicUsecase(musicRepo)
	musicService := service.NewMusicService(musicUsecase, music)
	httpServer := server.NewHTTPServer(confServer, musicService)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
