// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Music         *Music                 `protobuf:"bytes,2,opt,name=music,proto3" json:"music,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetMusic() *Music {
	if x != nil {
		return x.Music
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Music struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory scanned recursively for audio files. Empty disables the library
	// (the server still answers music.ping).
	MusicDir string `protobuf:"bytes,1,opt,name=music_dir,json=musicDir,proto3" json:"music_dir,omitempty"`
	// Public base URL used to build stream/cover URLs, e.g.
	// "http://192.168.1.10:8080". Empty derives it from the incoming request.
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// Optional static bearer token for the JSON-RPC endpoint. Empty disables RPC
	// authentication.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Optional HMAC secret used to sign stream/cover URLs. Empty falls back to
	// `token`; when both are empty URLs are unsigned.
	StreamSecret string `protobuf:"bytes,4,opt,name=stream_secret,json=streamSecret,proto3" json:"stream_secret,omitempty"`
	// Signed URL lifetime in seconds. Defaults to 3600.
	TokenTtl int64 `protobuf:"varint,5,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	// JSON-RPC path. Defaults to "/rpc".
	RpcPath string `protobuf:"bytes,6,opt,name=rpc_path,json=rpcPath,proto3" json:"rpc_path,omitempty"`
	// Stream path prefix. Defaults to "/stream".
	StreamPath string `protobuf:"bytes,7,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"`
	// Cover path prefix. Defaults to "/cover".
	CoverPath string `protobuf:"bytes,8,opt,name=cover_path,json=coverPath,proto3" json:"cover_path,omitempty"`
	// Audio file extensions to index (without the leading dot). Empty uses a
	// built-in list.
	Extensions []string `protobuf:"bytes,9,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Rescan interval. Zero disables periodic rescanning.
	RescanInterval *durationpb.Duration `protobuf:"bytes,10,opt,name=rescan_interval,json=rescanInterval,proto3" json:"rescan_interval,omitempty"`
	// Watch music_dir with fsnotify and rescan automatically when files are
	// added, removed or renamed. When false, only rescan_interval polling applies.
	Watch         bool `protobuf:"varint,11,opt,name=watch,proto3" json:"watch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Music) Reset() {
	*x = Music{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Music) ProtoMessage() {}

func (x *Music) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Music.ProtoReflect.Descriptor instead.
func (*Music) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Music) GetMusicDir() string {
	if x != nil {
		return x.MusicDir
	}
	return ""
}

func (x *Music) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Music) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Music) GetStreamSecret() string {
	if x != nil {
		return x.StreamSecret
	}
	return ""
}

func (x *Music) GetTokenTtl() int64 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

func (x *Music) GetRpcPath() string {
	if x != nil {
		return x.RpcPath
	}
	return ""
}

func (x *Music) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *Music) GetCoverPath() string {
	if x != nil {
		return x.CoverPath
	}
	return ""
}

func (x *Music) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Music) GetRescanInterval() *durationpb.Duration {
	if x != nil {
		return x.RescanInterval
	}
	return nil
}

func (x *Music) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"`\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12'\n" +
	"\x05music\x18\x02 \x01(\v2\x11.kratos.api.MusicR\x05music\"\xa0\x01\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xec\x02\n" +
	"\x05Music\x12\x1b\n" +
	"\tmusic_dir\x18\x01 \x01(\tR\bmusicDir\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rstream_secret\x18\x04 \x01(\tR\fstreamSecret\x12\x1b\n" +
	"\ttoken_ttl\x18\x05 \x01(\x03R\btokenTtl\x12\x19\n" +
	"\brpc_path\x18\x06 \x01(\tR\arpcPath\x12\x1f\n" +
	"\vstream_path\x18\a \x01(\tR\n" +
	"streamPath\x12\x1d\n" +
	"\n" +
	"cover_path\x18\b \x01(\tR\tcoverPath\x12\x1e\n" +
	"\n" +
	"extensions\x18\t \x03(\tR\n" +
	"extensions\x12B\n" +
	"\x0frescan_interval\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x0erescanInterval\x12\x14\n" +
	"\x05watch\x18\v \x01(\bR\x05watchB\"Z achero_server/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Music)(nil),               // 2: kratos.api.Music
	(*Server_HTTP)(nil),         // 3: kratos.api.Server.HTTP
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1, // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2, // 1: kratos.api.Bootstrap.music:type_name -> kratos.api.Music
	3, // 2: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	4, // 3: kratos.api.Music.rescan_interval:type_name -> google.protobuf.Duration
	4, // 4: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
